In [2]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [3]:
x =  np.arange(1,13).reshape((6,2))

In [4]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
 x = np.arange(1,28,dtype=np.float64).reshape((3,3,3))

In [6]:
x

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]]])

# Task 3 

In [8]:
arr = np.arange(9).reshape(3,3)

In [9]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr[:, [1, 0]] = arr[:, [0, 1]] 

In [12]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [14]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [15]:
zeros = np.zeros((4, 5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
x = np.zeros(10)

In [18]:
x[4] = 10;x[5]=20;

In [19]:
x

array([ 0.,  0.,  0.,  0., 10., 20.,  0.,  0.,  0.,  0.])

In [20]:
 x = np.arange(4, dtype=np.int64)

In [21]:
x

array([0, 1, 2, 3], dtype=int64)

In [22]:
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

In [23]:
x = np.full((2, 5), 6, dtype=np.uint)

In [24]:
x

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [27]:
a = np.arange(100)

In [31]:
a[2::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [32]:
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])

In [33]:
brr = np.array([1,2,3])

In [35]:
crr = np.subtract(arr, brr)

In [36]:
crr

array([[2, 1, 0],
       [3, 2, 1],
       [4, 3, 2]])

In [55]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a[a%2 == 1] = -1

In [57]:
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [18]:
arr = np.array([1,2,3])

In [ ]:
solution_array = np.hstack((np.repeat(a, 3), a, a, a))

In [24]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [25]:
a[(a > 5) & (a < 10)]

array([6, 9])

In [27]:

  sampleArray = np.arange(10, 34, 1)

In [28]:
sampleArray = sampleArray.reshape(8,3)

In [30]:
subArrays = np.split(sampleArray, 4)

In [31]:
subArrays

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [33]:

sampleArray  = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])

In [34]:
sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]

In [35]:
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]

In [36]:
sortArrayByColumn

array([[-4,  1,  7],
       [ 8,  2, -2],
       [ 6,  3,  9]])

In [37]:

    x = np.array([[1], [2], [3]])

In [38]:
y = np.array([[2], [3], [4]])

In [41]:
print(np.stack((x, y), axis=1))

[[[1]
  [2]]

 [[2]
  [3]]

 [[3]
  [4]]]
